#!/usr/bin/env python3
"""
Migration v3: Clear contaminated Polymarket state after sentinel filter fixes.

Actions:
1. Clear prediction_market_state namespace in state.json
2. Remove discovered_topics.json (forces fresh discovery scan)
3. Clear ALL PredictionMarketSentinel deferred triggers (strengthened from v2)

All modified files receive timestamped backups before changes.
"""

import json
import os
import shutil
from datetime import datetime

STATE_FILE = "data/state.json"
DISCOVERED_TOPICS_FILE = "data/discovered_topics.json"
DEFERRED_FILE = "data/deferred_triggers.json"
BACKUP_SUFFIX = f".backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}"


def backup_file(filepath: str) -> str:
    """Create timestamped backup. Returns backup path."""
    backup_path = filepath + BACKUP_SUFFIX
    shutil.copy2(filepath, backup_path)
    print(f"  📦 Backed up: {backup_path}")
    return backup_path


def clear_prediction_market_state():
    """Section 1: Clear contaminated PM state from state.json."""
    print("\n--- Section 1: Prediction Market State ---")

    if not os.path.exists(STATE_FILE):
        print(f"  ⏭️  No state file at {STATE_FILE}")
        return

    backup_file(STATE_FILE)

    with open(STATE_FILE, 'r') as f:
        state = json.load(f)

    pm_key = "prediction_market_state"
    if pm_key not in state:
        print(f"  ⏭️  No '{pm_key}' namespace found")
        return

    old_count = len(state[pm_key])
    print(f"  Clearing {old_count} contaminated entries:")
    for topic, data in state[pm_key].items():
        if isinstance(data, dict) and 'data' in data:
            slug = data['data'].get('slug', 'unknown')
            title = data['data'].get('title', 'unknown')
        else:
            slug, title = 'unknown', 'unknown'
        print(f"    ✗ {topic} → {slug} ({title[:50]})")

    state[pm_key] = {}

    with open(STATE_FILE, 'w') as f:
        json.dump(state, f, indent=2)
    print(f"  ✅ Cleared {old_count} entries from prediction_market_state")


def clear_discovered_topics():
    """Section 2: Remove discovered_topics.json to force fresh discovery."""
    print("\n--- Section 2: Discovered Topics ---")

    if not os.path.exists(DISCOVERED_TOPICS_FILE):
        print(f"  ⏭️  No file at {DISCOVERED_TOPICS_FILE}")
        return

    backup_file(DISCOVERED_TOPICS_FILE)
    os.remove(DISCOVERED_TOPICS_FILE)
    print(f"  ✅ Removed {DISCOVERED_TOPICS_FILE}. Fresh discovery will run on next cycle.")


def clear_pm_deferred_triggers():
    """Section 3: Clear ALL PredictionMarketSentinel deferred triggers.

    Strengthened from v2: removes ALL PM triggers regardless of payload content,
    since any trigger generated by the broken pipeline is suspect.
    """
    print("\n--- Section 3: Deferred Triggers (Strengthened) ---")

    if not os.path.exists(DEFERRED_FILE):
        print(f"  ⏭️  No file at {DEFERRED_FILE}")
        return

    with open(DEFERRED_FILE, 'r') as f:
        deferred = json.load(f)

    total_count = len(deferred)
    pm_triggers = [t for t in deferred if t.get('source') == 'PredictionMarketSentinel']
    other_triggers = [t for t in deferred if t.get('source') != 'PredictionMarketSentinel']

    if not pm_triggers:
        print(f"  ⏭️  No PredictionMarketSentinel triggers found ({total_count} total)")
        return

    backup_file(DEFERRED_FILE)

    print(f"  Removing {len(pm_triggers)} PM triggers:")
    for t in pm_triggers:
        print(f"    ✗ {t.get('source')}: {t.get('reason', 'unknown')[:60]}")

    with open(DEFERRED_FILE, 'w') as f:
        json.dump(other_triggers, f, indent=2)

    print(f"  ✅ Cleared {len(pm_triggers)} PM triggers, kept {len(other_triggers)} others")


def main():
    print("=" * 60)
    print("Polymarket State Migration v3")
    print(f"Timestamp: {datetime.now().isoformat()}")
    print("=" * 60)

    clear_prediction_market_state()
    clear_discovered_topics()
    clear_pm_deferred_triggers()

    print("\n" + "=" * 60)
    print("✅ Migration complete. Restart orchestrator for changes to take effect.")
    print("   - Discovery agent will re-scan on next cycle")
    print("   - Sentinel will re-resolve all topics with new filters")
    print("   - Orphaned cache entries will be pruned by Minor C")
    print("=" * 60)


if __name__ == "__main__":
    main()
